version: 2
project_name: cligram
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    # Install and setup bun, then build JS backend in a single shell command
    - /bin/bash -c 'curl -fsSL https://bun.sh/install | bash && export BUN_INSTALL="$HOME/.bun" && export PATH="$BUN_INSTALL/bin:$PATH" && cd js && bun install && bun run build'
    - mkdir -p internal/assets/resources
    - cp js/bin/cligram-js internal/assets/resources/cligram-js-backend
    # Then run the completion and manpage scripts
    - ./scripts/manpages.sh
    - ./scripts/completions.sh
builds:
  - id: cligram
    binary: cligram
    main: .
    ldflags: -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  -
    ids:
      - cligram
    format_overrides:
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
nfpms:
  - ids:
      - cligram
    vendor: kumneger0
    homepage:  https://github.com/kumneger0/cligram
    maintainer: "Kumneger wondimu <Kumnegerwondimu@gmail.com>"
    description: "CLI-based Telegram client"
    license: GPL-3.0
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./manpages/cligram.1.gz
        dst: /usr/share/man/man1/cligram.1.gz
        file_info:
          mode: 0644
      - src: ./completions/cligram.bash
        dst: /usr/share/bash-completion/completions/cligram
        file_info:
          mode: 0644
      - src: ./completions/cligram.fish
        dst: /usr/share/fish/vendor_completions.d/cligram.fish
        file_info:
          mode: 0644
      - src: ./completions/cligram.zsh
        dst:  /usr/share/zsh/vendor-completions/_cligram
        file_info:
          mode: 0644
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999