name: Publish cligram

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
      TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
      SESSION_STRING: ${{ secrets.SESSION_STRING }}

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: bun install
        working-directory: .

      # - name: Test
      #   run: bun test
      #   working-directory: .

      - name: lint 
        run: bun run lint:check
        working-directory: .

      - name: build
        run: bun run build
        working-directory: .

      - name: Publish to npm
        run: npm publish
        working-directory: .
        env:
          BUN_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
