name: Test and coverage

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Build application and assets
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        run: make build
          

      - name: Run tests
        run: make test

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        run: bash <(curl -s https://codecov.io/bash)